#!/bin/bash
# @sacloud-once
# @sacloud-desc サーバ作成後、WebブラウザでサーバのIPアドレスにアクセスしてください。
# @sacloud-desc http://サーバのIPアドレス/
# @sacloud-desc (このスクリプトは、CentOS6.XもしくはScientific Linux6.Xでのみ動作します)
# @sacloud-desc Concrete5ダウンロードURL 入力例: http://www.concrete5.org/download_file/-/view/74619/
# @sacloud-desc 最新版は http://concrete5-japan.org/ で確認してください。
# @sacloud-text required shellarg maxlen=100 DURL "Concrete5ダウンロードURL"
# @sacloud-text required shellarg maxlen=32 VERSION "Concrete5のバージョン (例: concrete5.7.3.1)"
# @sacloud-text required shellarg maxlen=32 DBNAME "MySQLのデータベース名 (例: concrete5)"
# @sacloud-text required shellarg maxlen=32 DBUSER "MySQLのユーザー名 (例: concrete5)"
# @sacloud-password required shellarg maxlen=32 DBPASS "MySQLのパスワード"
# @sacloud-password required shellarg maxlen=32 DBROOTPASS "MySQLのrootパスワード"
DURL=@@@DURL@@@
VERSION=@@@VERSION@@@
DBNAME=@@@DBNAME@@@
DBUSER=@@@DBUSER@@@
DBPASS=@@@DBPASS@@@
DBROOTPASS=@@@DBROOTPASS@@@
yum -y update
service iptables stop
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -I INPUT -p icmp --icmp-type 0 -j ACCEPT
iptables -I INPUT -p icmp --icmp-type 8 -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
service iptables save
service iptables start
chkconfig iptables on
yum -y install http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
cp -p /etc/yum.repos.d/nginx.repo /etc/yum.repos.d/nginx.repo.orig
sed -i 's/centos/mainline\/centos/' /etc/yum.repos.d/nginx.repo
yum -y install nginx
[ ! -f /etc/yum.repos.d/remi.repo ] && 
yum -y install http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
yum -y --enablerepo=remi install gd-last
yum --enablerepo=remi-php56 -y install php-cli php-common php-mbstring php-pdo php-xml php-mysqlnd php-gd php-pecl-apcu php-xmlrpc php-opcache php-fpm
yum -y install http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
yum -y install mysql-community-server
chkconfig mysqld on
service mysqld start
mysqladmin -u root password "${DBROOTPASS}"
mysql -u root -p${DBROOTPASS} -e "create database ${DBNAME} character set utf8;"
mysql -u root -p${DBROOTPASS} -e "GRANT ALL PRIVILEGES on ${DBNAME}.* to ${DBUSER}@localhost identified by \"${DBPASS}\";"
mysql -u root -p${DBROOTPASS} -e "DELETE FROM mysql.user WHERE User='';"
mysql -u root -p${DBROOTPASS} -e "DELETE FROM mysql.user WHERE User='root' AND Host IN (\"$(uname -n)\", '127.0.0.1', '::1');"
mysql -u root -p${DBROOTPASS} -e "FLUSH PRIVILEGES;"
cp -p /etc/php.ini /etc/php.ini.orig
sed -i 's/;date.timezone =/;##--@--##date.timezone =\ndate.timezone = Asia\/Tokyo/' /etc/php.ini
cp -p /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.orig
sed -i 's/^user = apache/;user = apache\nuser = nginx/' /etc/php-fpm.d/www.conf
sed -i 's/^group = apache/;group = apache\ngroup = nginx/' /etc/php-fpm.d/www.conf
chgrp nginx /var/lib/php/{session,wsdlcache}
service php-fpm start
chkconfig php-fpm on
mkdir /root/src
curl -L -o /root/src/${VERSION}.zip ${DURL} && \
unzip /root/src/${VERSION}.zip -d /root/src/
cp -pr /root/src/$(ls /root/src | grep ${VERSION} | grep -v zip$)/* /var/www/html/
chown -R nginx. /var/www/html/
cp -p /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig
sed -i "s/worker_processes[[:space:]]+[0-9]+/worker_processes $(cat /proc/cpuinfo | grep processor | wc -l)/g" /etc/nginx/nginx.conf
mkdir /etc/nginx/conf.d/BACKUP
mv /etc/nginx/conf.d/*.conf /etc/nginx/conf.d/BACKUP/
cat << _EOL_ | tee /etc/nginx/conf.d/000_VHOST.conf
server {
    server_name ${HOSTNAME};
    root /var/www/html;
    location / {
        index  index.php index.html index.htm;
    }
    if (\$uri ~ "^(.+?.php?)(/.*)\$") {
        set \$path_info \$2;
    }
    if (!-e \$request_filename) {
        rewrite ^(.+)\$ /index.php last;
    }
    location ~* .(js|css|png|jpg|jpeg|gif|ico)\$ {
        expires 24h;
        log_not_found off;
    }
        location ~ .php\$ {
        try_files \$uri = 404;
        fastcgi_split_path_info ^(.+.php)(/.+)\$;
        include fastcgi_params;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
    }
}
_EOL_
service nginx start
chkconfig nginx on
reboot
